### PR TITLE
Address vulnerabilities

### PR DESCRIPTION
**Pull request by anrikus**
Updated requirements.txt to address vulnerable dependencies.

### CODE REVIEW

**Review by hehehe47 — APPROVED** [review]

**Review by jinyoung-lim — COMMENTED** [review]
How did you test?

**Comment by Captainia** [comment]
> How did you test? Will the notebooks still run?

This is fine since the codes here are for reference, but what is the reason of not updating with latest content from code.amazon.com?

**Review by Captainia — APPROVED** [review]

**Comment by jinyoung-lim** [comment]
@Captainia  I see! Yeah @anrikus would it be quick enough for you to update with the latest content?

**Comment by anrikus** [comment]
The solution here are supposed to work on classic notebooks instances and not Sagemaker studio, as such, not keeping this in sync with the code.amazon.com version.

**Comment by anrikus** [comment]
@jinyoung-lim, the solution should still run as it is picking the artifacts from the prod bucket and not Github, also bypassing the requirements for testing.

**Comment by anrikus** [comment]
> How did you test? Will the notebooks still run?

This version is not in sync with the Studio version for now. The Studio version being maintained for the time being, the maintainability of the Github solution will be addressed later.

**Pull request merged**
